ALTER TABLE public.signals
ADD COLUMN IF NOT EXISTS ror numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ic numeric NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ic_lower numeric NOT NULL DEFAULT 0;